language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-26.1.0
    # The SDK version used to compile your project
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
  jdk: oraclejdk8
  licenses:
      # Check licenses: http://docs.travis-ci.com/user/languages/android/#Dealing-with-Licenses
      # By default Travis will accept all the licenses, but it's also possible to define a white list:
      # White list current android-sdk-license revision.
      # - 'android-sdk-license-5be876d5'
      # White list all android-sdk-license revisions.
      - 'android-sdk-license-.+'
      # White list all the licenses.
      - '.+'
  script:
   ./gradlew assembleRelease
