language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-26.0.2
    # The SDK version used to compile your project
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
  script:
   ./gradlew assembleRelease
